#!/usr/bin/env python3
"""Generate 200+ SKILL.md files for the Cyrene bundled skill library."""
import os

SKILLS = {
    "software-development": [
        ("code-review", "Review code for quality, security, and best practices", "Analyze code for bugs, security vulnerabilities, style issues, and suggest improvements."),
        ("refactor-function", "Refactor a function for clarity and performance", "Identify code smells, extract methods, reduce complexity, and improve naming."),
        ("write-unit-test", "Write unit tests for a given function or module", "Generate comprehensive unit tests covering edge cases, error paths, and happy paths."),
        ("debug-error", "Debug an error from stack trace or log output", "Analyze error messages, trace execution flow, identify root cause, and suggest fix."),
        ("git-workflow", "Manage git branches, commits, and merges", "Handle branching strategy, conflict resolution, rebasing, and PR creation."),
        ("api-design", "Design RESTful or GraphQL API endpoints", "Define endpoints, request/response schemas, authentication, and versioning."),
        ("dependency-update", "Update and audit project dependencies", "Check for outdated packages, security vulnerabilities, and breaking changes."),
        ("code-explain", "Explain what a piece of code does", "Break down code logic, identify patterns, and explain in plain language."),
        ("code-translate", "Translate code between programming languages", "Convert code while preserving logic, idioms, and language-specific best practices."),
        ("lint-fix", "Fix linting and formatting issues", "Apply consistent style rules, fix warnings, and ensure code passes CI checks."),
        ("type-annotation", "Add or improve type annotations", "Add type hints to Python, TypeScript types, or Rust type annotations for better safety."),
        ("mock-generator", "Generate mock objects for testing", "Create mock implementations of interfaces, services, and external dependencies."),
        ("changelog-generate", "Generate changelog from git history", "Parse commits, categorize changes, and produce a formatted changelog."),
        ("code-metrics", "Analyze code complexity and metrics", "Calculate cyclomatic complexity, code coverage, and identify hotspots."),
        ("pattern-suggest", "Suggest design patterns for a problem", "Analyze requirements and recommend appropriate design patterns with examples."),
        ("error-handling", "Implement robust error handling", "Design error types, propagation strategies, and user-friendly error messages."),
    ],
    "devops": [
        ("docker-compose", "Write Docker Compose configurations", "Define multi-container applications with networking, volumes, and environment variables."),
        ("ci-pipeline", "Create CI/CD pipeline configurations", "Set up GitHub Actions, GitLab CI, or Jenkins pipelines with proper stages."),
        ("terraform-module", "Write Terraform infrastructure modules", "Define cloud resources as code with proper state management and modularity."),
        ("k8s-deployment", "Create Kubernetes deployment manifests", "Write Deployments, Services, ConfigMaps, and Helm charts."),
        ("nginx-config", "Configure Nginx reverse proxy and load balancing", "Set up upstream servers, SSL termination, caching, and rate limiting."),
        ("monitoring-setup", "Set up monitoring and alerting", "Configure Prometheus, Grafana dashboards, and alert rules."),
        ("log-analysis", "Analyze application and system logs", "Parse log files, identify patterns, errors, and performance bottlenecks."),
        ("backup-strategy", "Design and implement backup strategies", "Plan backup schedules, retention policies, and disaster recovery procedures."),
        ("ssl-setup", "Configure SSL/TLS certificates", "Generate, install, and auto-renew certificates with Let's Encrypt."),
        ("ansible-playbook", "Write Ansible playbooks for automation", "Define server provisioning, configuration management, and deployment tasks."),
        ("caddy-config", "Configure Caddy web server", "Set up automatic HTTPS, reverse proxies, and static file serving."),
        ("systemd-service", "Create systemd service units", "Define services with proper restart policies, dependencies, and resource limits."),
        ("cron-management", "Manage system cron jobs and scheduled tasks", "Write cron expressions, systemd timers, and scheduled backup scripts."),
        ("firewall-rules", "Configure firewall rules and network security", "Set up iptables, ufw, or cloud security groups with proper ingress/egress rules."),
        ("container-security", "Harden container and Docker security", "Apply least privilege, scan images, manage secrets, and configure AppArmor/seccomp."),
    ],
    "data-science": [
        ("data-cleaning", "Clean and preprocess datasets", "Handle missing values, outliers, duplicates, and data type conversions."),
        ("eda-perform", "Perform exploratory data analysis", "Generate summary statistics, distributions, correlations, and visualizations."),
        ("feature-engineering", "Engineer features for ML models", "Create derived features, encode categoricals, normalize, and select relevant features."),
        ("model-train", "Train a machine learning model", "Select algorithm, tune hyperparameters, cross-validate, and evaluate performance."),
        ("data-viz", "Create data visualizations and charts", "Generate plots using matplotlib, seaborn, plotly, or other visualization libraries."),
        ("sql-query", "Write and optimize SQL queries", "Craft SELECT, JOIN, window functions, CTEs, and optimize query performance."),
        ("pandas-manipulate", "Manipulate data with pandas", "Filter, group, merge, pivot, and transform DataFrames efficiently."),
        ("statistical-test", "Perform statistical hypothesis tests", "Run t-tests, chi-square, ANOVA, and interpret p-values and confidence intervals."),
        ("notebook-export", "Export Jupyter notebooks to reports", "Convert notebooks to HTML, PDF, or slides with proper formatting."),
        ("ab-test-design", "Design A/B testing experiments", "Define metrics, sample size, duration, and statistical significance criteria."),
        ("time-series", "Analyze and forecast time series data", "Decompose trends, detect seasonality, and build forecasting models."),
        ("dimensionality-reduce", "Reduce dimensionality of datasets", "Apply PCA, t-SNE, UMAP for visualization and feature reduction."),
        ("data-pipeline", "Build data processing pipelines", "Create ETL/ELT pipelines with proper error handling and data validation."),
        ("web-scrape", "Scrape and extract data from websites", "Use requests, BeautifulSoup, or Scrapy to collect structured web data."),
    ],
    "research": [
        ("literature-review", "Conduct a literature review on a topic", "Search, summarize, and synthesize academic papers and sources."),
        ("summarize-article", "Summarize a long article or paper", "Extract key points, methodology, findings, and conclusions."),
        ("fact-check", "Fact-check claims against reliable sources", "Verify statements, find authoritative sources, and assess credibility."),
        ("topic-deep-dive", "Deep dive into a technical topic", "Research thoroughly, organize findings, and present structured knowledge."),
        ("compare-approaches", "Compare different technical approaches", "Analyze trade-offs, pros/cons, and recommend based on requirements."),
        ("technical-writing", "Write technical documentation or blog posts", "Create clear, well-structured technical content for various audiences."),
        ("citation-format", "Format citations and references", "Generate properly formatted references in APA, MLA, Chicago, or IEEE style."),
        ("competitive-analysis", "Analyze competitors and market landscape", "Research competing products, features, pricing, and market positioning."),
        ("patent-search", "Search and analyze patent databases", "Find relevant patents, analyze claims, and assess novelty."),
        ("trend-analysis", "Analyze trends in technology or market", "Track adoption curves, emerging technologies, and industry movements."),
        ("survey-design", "Design research surveys and questionnaires", "Create valid survey instruments with proper question types and scales."),
        ("experiment-design", "Design controlled experiments", "Define variables, control groups, randomization, and measurement protocols."),
    ],
    "creative": [
        ("brainstorm-ideas", "Brainstorm creative ideas for a project", "Generate diverse ideas using lateral thinking, SCAMPER, or mind mapping."),
        ("write-story", "Write a short story or narrative", "Create compelling characters, plot, dialogue, and narrative arc."),
        ("generate-names", "Generate names for projects, products, or brands", "Create memorable, meaningful, and available names with domain checks."),
        ("logo-concept", "Design logo concepts and descriptions", "Describe visual concepts, color schemes, and design rationale for logos."),
        ("write-poem", "Write poetry in various styles", "Compose poems in haiku, sonnet, free verse, or other forms."),
        ("content-repurpose", "Repurpose content across formats", "Convert blog posts to tweets, videos to scripts, or podcasts to articles."),
        ("email-draft", "Draft professional or personal emails", "Write clear, appropriate emails with proper tone and structure."),
        ("presentation-create", "Create presentation outlines and content", "Structure presentations with compelling narratives and visual slide descriptions."),
        ("social-media-post", "Write engaging social media posts", "Craft posts for Twitter, LinkedIn, Instagram with appropriate hashtags and tone."),
        ("ad-copy-write", "Write advertising copy and taglines", "Create persuasive copy that highlights benefits and drives action."),
        ("recipe-create", "Create or modify recipes", "Develop recipes with ingredients, instructions, nutritional info, and variations."),
        ("music-lyrics", "Write song lyrics", "Compose lyrics with rhyme, meter, theme, and emotional resonance."),
    ],
    "productivity": [
        ("task-prioritize", "Prioritize tasks using proven frameworks", "Apply Eisenhower matrix, MoSCoW, or RICE scoring to task lists."),
        ("meeting-notes", "Take and organize meeting notes", "Capture decisions, action items, and key discussion points."),
        ("email-triage", "Triage and organize email inbox", "Categorize, prioritize, and create action items from email backlog."),
        ("calendar-organize", "Organize calendar and time blocks", "Schedule focused work, meetings, and breaks for optimal productivity."),
        ("project-plan", "Create project plans and timelines", "Define milestones, dependencies, resources, and critical path."),
        ("decision-matrix", "Create decision matrices for complex choices", "Weight criteria, score options, and recommend the best choice."),
        ("sop-create", "Create standard operating procedures", "Document repeatable processes with clear steps and quality checks."),
        ("habit-tracker", "Design habit tracking systems", "Create accountability frameworks, streak tracking, and motivation strategies."),
        ("template-create", "Create reusable document templates", "Design templates for reports, proposals, invoices, and other documents."),
        ("goal-setting", "Set and track SMART goals", "Define specific, measurable goals with milestones and accountability."),
        ("knowledge-base", "Build and maintain a personal knowledge base", "Organize notes, bookmarks, and learnings in a searchable system."),
        ("workflow-automate", "Automate repetitive workflows", "Identify automation opportunities and create scripts or integrations."),
    ],
    "communication": [
        ("slack-message", "Draft Slack messages with appropriate tone", "Write clear, professional Slack messages that drive action."),
        ("report-write", "Write structured business or technical reports", "Create reports with executive summary, findings, and recommendations."),
        ("feedback-give", "Give constructive feedback", "Deliver actionable feedback using SBI or similar frameworks."),
        ("negotiation-prepare", "Prepare for negotiations", "Research positions, identify BATNA, and craft opening offers."),
        ("status-update", "Write project status updates", "Communicate progress, blockers, and next steps clearly."),
        ("proposal-write", "Write business or project proposals", "Create compelling proposals with scope, timeline, and budget."),
        ("interview-prepare", "Prepare for job interviews", "Research the company, practice answers, and prepare questions."),
        ("conflict-resolve", "Navigate workplace conflicts", "Identify root causes, find common ground, and propose solutions."),
        ("announcement-draft", "Draft team or company announcements", "Communicate changes, updates, and news with appropriate tone."),
        ("documentation-write", "Write user-facing documentation", "Create clear, organized docs with examples and troubleshooting."),
        ("translation-assist", "Assist with language translation", "Translate text while preserving nuance, idioms, and cultural context."),
        ("speech-write", "Write speeches and presentations", "Craft compelling speeches with clear structure and rhetorical devices."),
    ],
    "security": [
        ("vulnerability-scan", "Analyze code for security vulnerabilities", "Check for SQL injection, XSS, CSRF, and other OWASP Top 10 issues."),
        ("password-audit", "Audit password policies and practices", "Review password requirements, storage, and breach exposure."),
        ("security-review", "Perform security architecture review", "Assess authentication, authorization, encryption, and attack surface."),
        ("incident-respond", "Handle security incident response", "Contain, investigate, eradicate, and recover from security incidents."),
        ("compliance-check", "Check compliance with security standards", "Verify adherence to SOC2, GDPR, HIPAA, or PCI-DSS requirements."),
        ("pen-test-guide", "Guide penetration testing activities", "Plan and execute pen tests, document findings, and recommend fixes."),
        ("secret-scan", "Scan for exposed secrets and credentials", "Check code, configs, and logs for leaked API keys, tokens, and passwords."),
        ("network-audit", "Audit network configuration and security", "Review firewall rules, open ports, and network segmentation."),
        ("access-review", "Review user access and permissions", "Audit user roles, permissions, and implement least privilege."),
        ("crypto-implement", "Implement cryptographic operations correctly", "Use proper encryption, hashing, signing, and key management."),
        ("threat-model", "Create threat models for applications", "Identify assets, threats, vulnerabilities, and countermeasures."),
        ("supply-chain-audit", "Audit software supply chain security", "Verify dependency integrity, check for typosquatting, and assess SBOM."),
    ],
    "finance": [
        ("budget-create", "Create personal or project budgets", "Plan income, expenses, savings goals, and track spending."),
        ("expense-track", "Track and categorize expenses", "Log transactions, categorize spending, and identify savings opportunities."),
        ("invoice-generate", "Generate professional invoices", "Create itemized invoices with payment terms and tax calculations."),
        ("tax-prepare", "Prepare for tax filing", "Organize documents, identify deductions, and estimate tax liability."),
        ("investment-analyze", "Analyze investment opportunities", "Evaluate stocks, funds, or real estate using fundamental analysis."),
        ("financial-report", "Generate financial reports and summaries", "Create P&L, balance sheets, and cash flow statements."),
        ("pricing-strategy", "Develop pricing strategies", "Analyze costs, competition, and willingness to pay for optimal pricing."),
        ("roi-calculate", "Calculate return on investment", "Compute ROI, NPV, IRR, and payback period for projects."),
        ("contract-review", "Review financial contracts and terms", "Analyze payment terms, penalties, and financial obligations."),
        ("revenue-forecast", "Forecast revenue and sales", "Build revenue models with seasonality, growth rates, and scenarios."),
    ],
    "smart-home": [
        ("automation-create", "Create home automation rules", "Define triggers, conditions, and actions for smart home devices."),
        ("device-troubleshoot", "Troubleshoot smart home device issues", "Diagnose connectivity, configuration, and compatibility problems."),
        ("energy-optimize", "Optimize home energy usage", "Analyze consumption patterns and suggest efficiency improvements."),
        ("security-camera", "Configure and manage security cameras", "Set up recording, motion detection, and alert systems."),
        ("voice-assistant", "Configure voice assistant integrations", "Set up routines, skills, and custom commands for Alexa, Google, or Siri."),
        ("network-optimize", "Optimize home network performance", "Configure WiFi, QoS, and troubleshoot connectivity issues."),
        ("media-setup", "Set up home media systems", "Configure Plex, Sonos, or other media streaming solutions."),
        ("iot-protocol", "Configure IoT protocols and hubs", "Set up Zigbee, Z-Wave, Matter, or Thread networks and bridges."),
    ],
    "ai-ml": [
        ("prompt-engineer", "Engineer effective prompts for LLMs", "Craft prompts with clear instructions, examples, and constraints."),
        ("rag-build", "Build retrieval-augmented generation systems", "Design vector stores, chunking strategies, and retrieval pipelines."),
        ("fine-tune-guide", "Guide fine-tuning of language models", "Prepare training data, configure hyperparameters, and evaluate results."),
        ("agent-design", "Design AI agent architectures", "Plan tool use, memory, planning, and multi-agent coordination."),
        ("embedding-generate", "Generate and work with text embeddings", "Create embeddings for semantic search, clustering, and classification."),
        ("llm-evaluate", "Evaluate LLM outputs and performance", "Design benchmarks, measure quality, and compare model performance."),
        ("chatbot-build", "Build conversational chatbot systems", "Design conversation flows, context management, and response generation."),
        ("image-prompt", "Create prompts for image generation", "Craft detailed prompts for DALL-E, Midjourney, or Stable Diffusion."),
        ("model-deploy", "Deploy ML models to production", "Set up serving infrastructure, monitoring, and versioning."),
        ("data-label", "Design data labeling workflows", "Create annotation guidelines, quality checks, and labeling pipelines."),
        ("ml-pipeline", "Build end-to-end ML pipelines", "Design data ingestion, training, evaluation, and deployment pipelines."),
        ("bias-detect", "Detect and mitigate bias in ML models", "Test for fairness across demographics and apply debiasing techniques."),
    ],
    "web-development": [
        ("react-component", "Build React components", "Create reusable, accessible React components with proper state management."),
        ("css-layout", "Create responsive CSS layouts", "Build layouts using Flexbox, Grid, and responsive design principles."),
        ("api-integrate", "Integrate third-party APIs", "Handle authentication, error handling, and data mapping for external APIs."),
        ("form-validate", "Implement form validation", "Add client-side and server-side validation with proper error messages."),
        ("seo-optimize", "Optimize web pages for SEO", "Improve meta tags, structured data, performance, and accessibility."),
        ("perf-optimize", "Optimize web application performance", "Reduce bundle size, lazy load, cache, and optimize critical rendering path."),
        ("auth-implement", "Implement authentication systems", "Set up JWT, OAuth2, session management, and role-based access control."),
        ("pwa-build", "Build progressive web applications", "Add service workers, offline support, and install prompts."),
        ("websocket-implement", "Implement WebSocket connections", "Set up real-time bidirectional communication with proper error handling."),
        ("graphql-schema", "Design GraphQL schemas and resolvers", "Define types, queries, mutations, and optimize resolver performance."),
        ("nextjs-setup", "Set up Next.js applications", "Configure SSR, SSG, API routes, and deployment."),
        ("tailwind-style", "Style applications with Tailwind CSS", "Create responsive, consistent designs using utility classes."),
    ],
    "mobile-development": [
        ("flutter-widget", "Build Flutter widgets", "Create custom widgets with proper state management and animations."),
        ("react-native-screen", "Build React Native screens", "Create cross-platform screens with navigation and proper styling."),
        ("ios-swiftui", "Build iOS views with SwiftUI", "Create declarative UI with proper data flow and animations."),
        ("android-jetpack", "Build Android UI with Jetpack Compose", "Create modern Android UI with proper lifecycle management."),
        ("push-notification", "Implement push notifications", "Set up FCM/APNs with proper handling for foreground and background."),
        ("offline-sync", "Implement offline data synchronization", "Handle conflict resolution, queue operations, and sync when online."),
        ("deep-link", "Implement deep linking", "Handle universal links, app links, and custom URL schemes."),
        ("app-store-prepare", "Prepare app for store submission", "Generate screenshots, write descriptions, and handle review guidelines."),
    ],
    "database": [
        ("schema-design", "Design database schemas", "Create normalized schemas with proper relationships, indexes, and constraints."),
        ("migration-create", "Create database migrations", "Write up/down migrations with proper data transformations and rollback support."),
        ("query-optimize", "Optimize slow database queries", "Analyze execution plans, add indexes, and rewrite queries for performance."),
        ("redis-implement", "Implement Redis caching strategies", "Design cache invalidation, TTLs, and data structures for optimal caching."),
        ("mongodb-model", "Design MongoDB document models", "Create embedded vs referenced schemas with proper indexing strategies."),
        ("backup-restore", "Implement database backup and restore", "Set up automated backups, point-in-time recovery, and restore procedures."),
        ("data-migrate", "Migrate data between databases", "Plan and execute data migrations with validation and rollback capability."),
        ("connection-pool", "Configure database connection pooling", "Set up pool sizes, timeouts, and health checks for optimal throughput."),
    ],
    "networking": [
        ("dns-configure", "Configure DNS records and resolution", "Set up A, AAAA, CNAME, MX, TXT records and DNSSEC."),
        ("load-balancer", "Configure load balancing", "Set up round-robin, least connections, or weighted load balancing."),
        ("vpn-setup", "Set up VPN connections", "Configure WireGuard, OpenVPN, or IPSec tunnels for secure access."),
        ("cdn-configure", "Configure CDN for content delivery", "Set up caching rules, edge functions, and origin shields."),
        ("tcp-debug", "Debug TCP/IP connectivity issues", "Use netstat, tcpdump, and traceroute to diagnose network problems."),
        ("proxy-configure", "Configure HTTP/SOCKS proxies", "Set up forward and reverse proxies with authentication and logging."),
    ],
    "testing": [
        ("e2e-test-write", "Write end-to-end tests", "Create browser automation tests with Playwright or Cypress."),
        ("integration-test", "Write integration tests", "Test component interactions with proper test isolation and fixtures."),
        ("load-test", "Design and run load tests", "Create load test scenarios with k6, JMeter, or Locust."),
        ("test-strategy", "Define testing strategy for a project", "Plan test pyramid, coverage targets, and testing workflows."),
        ("contract-test", "Write contract tests for APIs", "Define and verify API contracts between services."),
        ("property-test", "Write property-based tests", "Define invariants and generate random inputs to find edge cases."),
        ("snapshot-test", "Implement snapshot testing", "Create and manage visual and data snapshot tests."),
        ("fuzz-test", "Design fuzz testing harnesses", "Create fuzz targets for parsers, validators, and input handlers."),
    ],
    "documentation": [
        ("api-doc-write", "Write API documentation", "Create OpenAPI/Swagger specs with examples and authentication details."),
        ("readme-write", "Write project README files", "Create comprehensive READMEs with installation, usage, and contribution guides."),
        ("architecture-doc", "Document system architecture", "Create architecture decision records, diagrams, and component descriptions."),
        ("user-guide-write", "Write user guides and tutorials", "Create step-by-step guides with screenshots and troubleshooting sections."),
        ("changelog-maintain", "Maintain project changelogs", "Keep changelogs updated following Keep a Changelog format."),
        ("contributing-guide", "Write contributing guidelines", "Define code style, PR process, issue templates, and development setup."),
        ("adr-write", "Write Architecture Decision Records", "Document technical decisions with context, options, and rationale."),
    ],
    "design": [
        ("ui-mockup", "Create UI mockup descriptions", "Describe wireframes, layouts, and component hierarchies for UI design."),
        ("color-palette", "Design color palettes", "Create accessible, harmonious color schemes with proper contrast ratios."),
        ("typography-select", "Select and pair typography", "Choose font combinations that match brand personality and readability needs."),
        ("icon-system", "Design icon systems", "Create consistent icon sets with proper sizing, style, and meaning."),
        ("design-system", "Build design system components", "Define tokens, components, patterns, and usage guidelines."),
        ("ux-flow", "Design user experience flows", "Map user journeys, identify friction points, and optimize conversion."),
        ("accessibility-audit", "Audit accessibility compliance", "Check WCAG compliance, screen reader support, and keyboard navigation."),
    ],
    "marketing": [
        ("seo-strategy", "Develop SEO strategy", "Research keywords, optimize content, and build link strategies."),
        ("content-calendar", "Create content marketing calendars", "Plan blog posts, social media, and email campaigns with themes."),
        ("analytics-setup", "Set up marketing analytics", "Configure Google Analytics, conversion tracking, and attribution models."),
        ("landing-page", "Design landing page content", "Write headlines, CTAs, and persuasive copy for conversion optimization."),
        ("email-campaign", "Design email marketing campaigns", "Create drip sequences, newsletters, and promotional emails."),
        ("market-research", "Conduct market research", "Analyze target audience, market size, and competitive landscape."),
        ("brand-voice", "Define brand voice and messaging", "Create tone guidelines, key messages, and brand story."),
        ("growth-hack", "Identify growth hacking opportunities", "Find viral loops, referral programs, and low-cost acquisition channels."),
    ],
    "personal-assistant": [
        ("daily-planner", "Plan daily schedule and priorities", "Organize tasks, meetings, and focus time for maximum productivity."),
        ("travel-plan", "Plan travel itineraries", "Research destinations, book accommodations, and create day-by-day plans."),
        ("learning-plan", "Create learning plans and curricula", "Design structured learning paths with resources, milestones, and practice."),
        ("health-track", "Track health and fitness goals", "Monitor exercise, nutrition, sleep, and wellness metrics."),
        ("journal-prompt", "Generate journal prompts and reflections", "Create thoughtful prompts for self-reflection and personal growth."),
        ("gift-suggest", "Suggest gifts for occasions", "Recommend thoughtful gifts based on interests, budget, and relationship."),
        ("resume-write", "Write and optimize resumes", "Create targeted resumes with quantified achievements and proper formatting."),
        ("cover-letter", "Write cover letters for job applications", "Craft personalized cover letters that highlight relevant experience."),
    ],
}

def write_skill(category, slug, description, instructions):
    path = f"/Users/a/Sites/cyrene/skills/{category}/{slug}.md"
    content = f"""---
name: {slug}
description: {description}
category: {category}
version: 1
---

{instructions}
"""
    with open(path, "w") as f:
        f.write(content.lstrip())

total = 0
for category, skills in SKILLS.items():
    for slug, desc, instructions in skills:
        write_skill(category, slug, desc, instructions)
        total += 1

print(f"Generated {total} bundled skills")
